### ISSUE TITLE
CrashLoopBackOff

### ISSUE THREAD

**Issue by dyipon** [dcherman/image-cache-daemon#10]
Hi,

i just tried to use image-cache-daemon under k3s, but the all daemonset give the next error on start:
"standard_init_linux.go:228: exec user process caused: no such file or directory"

Can I get any help? :)

thanks

**Comment by dcherman** [comment]
Was able to reproduce it.  I'm betting it's because of the typo in `CGO_ENABLED` in the [Makefile](https://github.com/dcherman/image-cache-daemon/blob/01614abee70d84c17fe917f92b176d7bd9aee1ca/Makefile#L9).  I'll test a fix and get it deployed.

Thanks for the bug report!
