### ISSUE TITLE
flags does not work?

### ISSUE THREAD

**Issue by dyipon** [dcherman/image-cache-daemon#12]
Hi,

I would like to get less noise in logs, so I tried to setup the following flags/args, but did not working:
   args: ['--watch-argo-cron-workflows', 'false', '--watch-argo-cluster-workflow-templates', 'false', '--watch-argo-workflow-templates', 'false' ]

still getting errors:
 2022-03-07T08:21:17.356951222+01:00 E0307 07:21:17.356750       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.0/tools/cache/reflector.go:167: Failed to watch *v1alpha1.WorkflowTemplate: failed to list *v1alpha1.WorkflowTemplate: workflowtemplates.arg...

Is there any other way to allow only the ConfigMaps watcher?

**Comment by dcherman** [comment]
Hi,

Those are boolean flags (which are normally governed by the presence/absence of the flags), so having a space in there won't work for those particular ones I think.  Try this, it worked for me locally:

```yaml
args: ['--watch-argo-cron-workflows=false', '--watch-argo-cluster-workflow-templates=false', '--watch-argo-workflow-templates=false' ]
```

**Comment by dyipon** [comment]
thanks!
